name: Lint Python code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install flake8 and related packages
        run: python -m pip install -r python_requirements.txt
      - name: Check the repository's Python code
        run: python -m flake8 .
      - name: Check the repository's Jupyter notebooks
        run: python -m nbqa flake8 **/*.ipynb
